# Generated by Django 4.2.16 on 2025-01-19 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='suppliers',
            new_name='supplier',
        ),
    ]
