# Generated by Django 4.2.16 on 2025-01-29 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='username',
        ),
    ]
