# Generated by Django 4.2.16 on 2025-01-26 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_comment_delete_itemreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='bike',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.bike'),
        ),
    ]
